**1. Research Question**

Which is the most successful movie genre in the dataset? Is the movie that grosses the most also the most popular among viewers? Does the movie with the most popular actor also have the highest grossing?  Which year had the longest run time of movies? What are the top 10 movies based on rating frequency? 

**2. Justification - Why is this relevant to you or industry?**

As someone who consumes movies as a hobby, I find it interesting to understand the consumer culture and what factors drive a movie to success. I am also curious about the difference between viewer popularity and total gross. 

**3. Data Source - Did you find this data online or collect yourself?  provide links**

The data set is collected from kaggle.com,[https://www.kaggle.com/datasets/bharatnatrayn/movies-dataset-for-feature-extracion-prediction], and then stored on my GitHub [https://github.com/Raji030/data602_project_data/blob/main/movies.csv] for further use.

**4. Libraries potentially being used**

*   Pandas - Given the data set is a CSV file, this library will be used for data manipulation and analysis. 
*   Numpy - This library will be used for doing mathematical operations on numerical data.
*   Matplotlib - This library will be used for data visualization.
*   Scikit-Learn - There may be opportunities to use scikit-learn, for developing movie recommendation systems. 
*   Other libraries may be used as needed. 

**5. EDA and summary statistics**

The summary statistics is given below. From the initial inspection, it is seen that the dataset contains 9,999 rows and 9 columns. The columns include information such as the movie title, year of release, genre, duration, rating, director, actors, and gross income. There are also missing values in the year, genre, rating,votes, run time and gross columns. In this dataset, the target variable is not clearly defined. We could potentially use the gross income as a proxy for success and explore its distribution along with other movie features' exploratory data analysis and visualization by using histograms, bar plots, line plots etc. Moreover, the mean of the movie rating is 6.92 and the standard deviation of the movie rating is 1.22. Moreover, the mean of the movie run time is 68.69 minutes and the standard deviation of the movie run time is 47.26 minutes.

In [20]:
import pandas as pd
url="https://raw.githubusercontent.com/Raji030/data602_project_data/main/movies.csv"
df=pd.read_csv(url)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [21]:
df.shape

(9999, 9)

In [22]:
missing_values = df.isnull().sum()
print(missing_values)

MOVIES         0
YEAR         644
GENRE         80
RATING      1820
ONE-LINE       0
STARS          0
VOTES       1820
RunTime     2958
Gross       9539
dtype: int64

In [23]:
df.describe()

            RATING      RunTime
count  8179.000000  7041.000000
mean      6.921176    68.688539
std       1.220232    47.258056
min       1.100000     1.000000
25%       6.200000    36.000000
50%       7.100000    60.000000
75%       7.800000    95.000000
max       9.900000   853.000000